# Generated by Django 6.0.6 on 2026-06-13 18:08

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('name_ar', models.CharField(max_length=150, null=True)),
                ('name_en', models.CharField(max_length=150, null=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_title_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_description', models.TextField(blank=True)),
                ('seo_description_ar', models.TextField(blank=True, null=True)),
                ('seo_description_en', models.TextField(blank=True, null=True)),
                ('review_content', ckeditor.fields.RichTextField(blank=True)),
                ('review_content_ar', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('review_content_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('min_deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('withdrawal_time', models.CharField(blank=True, max_length=100)),
                ('withdrawal_time_ar', models.CharField(blank=True, max_length=100, null=True)),
                ('withdrawal_time_en', models.CharField(blank=True, max_length=100, null=True)),
                ('base_currencies', models.CharField(blank=True, help_text='e.g. USD, EUR, GBP', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deposit_limit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brokers', to='categories.depositlimit')),
                ('financial_assets', models.ManyToManyField(blank=True, related_name='brokers', to='categories.financialasset')),
                ('headquarters', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brokers', to='categories.headquarters')),
                ('islamic_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brokers', to='categories.islamicaccount')),
                ('regulators', models.ManyToManyField(blank=True, related_name='brokers', to='categories.regulator')),
                ('trading_platforms', models.ManyToManyField(blank=True, related_name='brokers', to='categories.tradingplatform')),
            ],
        ),
        migrations.CreateModel(
            name='BrokerFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('question_ar', models.CharField(max_length=255, null=True)),
                ('question_en', models.CharField(max_length=255, null=True)),
                ('answer', models.TextField()),
                ('answer_ar', models.TextField(null=True)),
                ('answer_en', models.TextField(null=True)),
                ('order', models.IntegerField(default=0)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='brokers.broker')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
