# Generated by Django 6.0.6 on 2026-06-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brokers/logos/'),
        ),
    ]
