# Generated by Django 6.0.6 on 2026-06-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0002_broker_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='logo_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='broker',
            name='logo_alt_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='logo_alt_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
