# Generated by Django 6.0.6 on 2026-06-14 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0003_broker_logo_alt_broker_logo_alt_ar_and_more'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='asset_variety',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='broker',
            name='cons',
            field=models.TextField(blank=True, help_text='One disadvantage per line / عيب واحد في كل سطر'),
        ),
        migrations.AddField(
            model_name='broker',
            name='cons_ar',
            field=models.TextField(blank=True, help_text='One disadvantage per line / عيب واحد في كل سطر', null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='cons_en',
            field=models.TextField(blank=True, help_text='One disadvantage per line / عيب واحد في كل سطر', null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='custom_terminal_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='custom_terminal_description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='custom_terminal_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='custom_terminal_image',
            field=models.ImageField(blank=True, null=True, upload_to='brokers/terminals/'),
        ),
        migrations.AddField(
            model_name='broker',
            name='custom_terminal_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='broker',
            name='custom_terminal_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='custom_terminal_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='customer_support',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='broker',
            name='execution_speed',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='broker',
            name='pros',
            field=models.TextField(blank=True, help_text='One advantage per line / ميزة واحدة في كل سطر'),
        ),
        migrations.AddField(
            model_name='broker',
            name='pros_ar',
            field=models.TextField(blank=True, help_text='One advantage per line / ميزة واحدة في كل سطر', null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='pros_en',
            field=models.TextField(blank=True, help_text='One advantage per line / ميزة واحدة في كل سطر', null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.5, max_digits=3),
        ),
        migrations.AddField(
            model_name='broker',
            name='verdict_quote',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='verdict_quote_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='verdict_quote_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='verdict_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='verdict_text_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='verdict_text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BrokerAccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_ar', models.CharField(max_length=100, null=True)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('min_deposit', models.CharField(max_length=100)),
                ('min_deposit_ar', models.CharField(max_length=100, null=True)),
                ('min_deposit_en', models.CharField(max_length=100, null=True)),
                ('spread_from', models.CharField(max_length=100)),
                ('spread_from_ar', models.CharField(max_length=100, null=True)),
                ('spread_from_en', models.CharField(max_length=100, null=True)),
                ('commission', models.CharField(max_length=100)),
                ('commission_ar', models.CharField(max_length=100, null=True)),
                ('commission_en', models.CharField(max_length=100, null=True)),
                ('leverage', models.CharField(max_length=100)),
                ('leverage_ar', models.CharField(max_length=100, null=True)),
                ('leverage_en', models.CharField(max_length=100, null=True)),
                ('order', models.IntegerField(default=0)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_types', to='brokers.broker')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BrokerPlatformTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_ar', models.CharField(max_length=100, null=True)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('subtitle', models.CharField(max_length=100)),
                ('subtitle_ar', models.CharField(max_length=100, null=True)),
                ('subtitle_en', models.CharField(max_length=100, null=True)),
                ('order', models.IntegerField(default=0)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_tabs', to='brokers.broker')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BrokerRegulator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=100)),
                ('status', models.CharField(default='AUTHORIZED', max_length=100)),
                ('status_ar', models.CharField(default='AUTHORIZED', max_length=100, null=True)),
                ('status_en', models.CharField(default='AUTHORIZED', max_length=100, null=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_regulators', to='brokers.broker')),
                ('regulator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.regulator')),
            ],
        ),
    ]
