# Generated by Django 5.2.15 on 2026-06-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0004_broker_asset_variety_broker_cons_broker_cons_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broker',
            name='cons_ar',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='custom_terminal_description_ar',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='custom_terminal_title_ar',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='logo_alt_ar',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='pros_ar',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='review_content_ar',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='seo_description_ar',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='seo_title_ar',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='verdict_quote_ar',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='verdict_text_ar',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='withdrawal_time_ar',
        ),
        migrations.RemoveField(
            model_name='brokeraccounttype',
            name='commission_ar',
        ),
        migrations.RemoveField(
            model_name='brokeraccounttype',
            name='leverage_ar',
        ),
        migrations.RemoveField(
            model_name='brokeraccounttype',
            name='min_deposit_ar',
        ),
        migrations.RemoveField(
            model_name='brokeraccounttype',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='brokeraccounttype',
            name='spread_from_ar',
        ),
        migrations.RemoveField(
            model_name='brokerfaq',
            name='answer_ar',
        ),
        migrations.RemoveField(
            model_name='brokerfaq',
            name='question_ar',
        ),
        migrations.RemoveField(
            model_name='brokerplatformtab',
            name='subtitle_ar',
        ),
        migrations.RemoveField(
            model_name='brokerplatformtab',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='brokerregulator',
            name='status_ar',
        ),
        migrations.AlterField(
            model_name='broker',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='brokeraccounttype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='brokerfaq',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='brokerplatformtab',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='brokerregulator',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
