# Generated by Django 5.2.15 on 2026-06-14 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0005_remove_broker_cons_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broker',
            name='cons_en',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='custom_terminal_description_en',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='custom_terminal_title_en',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='logo_alt_en',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='pros_en',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='review_content_en',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='seo_description_en',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='seo_title_en',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='verdict_quote_en',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='verdict_text_en',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='withdrawal_time_en',
        ),
        migrations.RemoveField(
            model_name='brokeraccounttype',
            name='commission_en',
        ),
        migrations.RemoveField(
            model_name='brokeraccounttype',
            name='leverage_en',
        ),
        migrations.RemoveField(
            model_name='brokeraccounttype',
            name='min_deposit_en',
        ),
        migrations.RemoveField(
            model_name='brokeraccounttype',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='brokeraccounttype',
            name='spread_from_en',
        ),
        migrations.RemoveField(
            model_name='brokerfaq',
            name='answer_en',
        ),
        migrations.RemoveField(
            model_name='brokerfaq',
            name='question_en',
        ),
        migrations.RemoveField(
            model_name='brokerplatformtab',
            name='subtitle_en',
        ),
        migrations.RemoveField(
            model_name='brokerplatformtab',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='brokerregulator',
            name='status_en',
        ),
    ]
