# Generated by Django 5.2.15 on 2026-06-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0006_remove_broker_cons_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='account_opening_link',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
