# Generated by Django 5.2.15 on 2026-06-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0007_broker_account_opening_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='verdict_sentiment',
            field=models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], default='neutral', max_length=20),
        ),
    ]
