# Generated by Django 5.2.15 on 2026-06-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0008_broker_verdict_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='local_offices',
            field=models.TextField(blank=True, help_text='One office per line / مكتب واحد في كل سطر'),
        ),
    ]
