# Generated by Django 6.0.6 on 2026-06-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0012_broker_founded_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='review_count',
            field=models.PositiveIntegerField(default=150, help_text='Number of reviews to display', verbose_name='Review Count'),
        ),
    ]
