# Generated by Django 5.2.15 on 2026-06-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_featured_image_alt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content_ar',
        ),
        migrations.RemoveField(
            model_name='article',
            name='featured_image_alt_ar',
        ),
        migrations.RemoveField(
            model_name='article',
            name='seo_description_ar',
        ),
        migrations.RemoveField(
            model_name='article',
            name='seo_title_ar',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='articlefaq',
            name='answer_ar',
        ),
        migrations.RemoveField(
            model_name='articlefaq',
            name='question_ar',
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='articlefaq',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
