# Generated by Django 5.2.15 on 2026-06-14 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_remove_article_content_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='featured_image_alt_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='seo_description_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='seo_title_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='articlefaq',
            name='answer_en',
        ),
        migrations.RemoveField(
            model_name='articlefaq',
            name='question_en',
        ),
    ]
