# Generated by Django 5.2.15 on 2026-06-14 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='broker',
        ),
    ]
