# Generated by Django 6.0.6 on 2026-06-14 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('best_brokers', '0002_bestbrokerslist_featured_image_alt_and_more'),
        ('brokers', '0003_broker_logo_alt_broker_logo_alt_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_broker_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_pos_1', to='brokers.broker')),
                ('featured_broker_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_pos_2', to='brokers.broker')),
                ('featured_broker_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_pos_3', to='brokers.broker')),
                ('featured_list_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_list_pos_1', to='best_brokers.bestbrokerslist')),
                ('featured_list_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_list_pos_2', to='best_brokers.bestbrokerslist')),
                ('featured_list_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_list_pos_3', to='best_brokers.bestbrokerslist')),
                ('featured_list_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_list_pos_4', to='best_brokers.bestbrokerslist')),
                ('hero_featured_broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_featured', to='brokers.broker')),
            ],
            options={
                'verbose_name': 'Homepage Settings',
                'verbose_name_plural': 'Homepage Settings',
            },
        ),
    ]
