# Generated by Django 6.0.6 on 2026-06-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_homepagesettings_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=100)),
                ('title_ar', models.CharField(max_length=100)),
                ('url_or_route', models.CharField(max_length=255)),
                ('column', models.CharField(choices=[('col2', 'Quick Links (Column 2)'), ('col3', 'Legal Links (Column 3)')], default='col2', max_length=10)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FooterRegulatoryBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_en', models.CharField(max_length=100)),
                ('text_ar', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeaderLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=100)),
                ('title_ar', models.CharField(max_length=100)),
                ('url_or_route', models.CharField(help_text='Can be a relative path e.g. /compare/ or named route home, compare_list, broker_directory, article_directory', max_length=255)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_brand_name', models.CharField(default='Brokers Times', max_length=100)),
                ('footer_about_en', models.TextField(default='Your number one platform for reviewing and evaluating trading brokers in the Arab world. Transparency, accuracy, and reliability in reviews to help you choose the best broker for your needs.')),
                ('footer_about_ar', models.TextField(default='منصتكم الأولى لمراجعة وتقييم شركات التداول في العالم العربي. شفافية ودقة وموثوقية في التقييمات لمساعدتك في اختيار الوسيط الأنسب لاحتياجاتك.')),
                ('footer_risk_warning_en', models.TextField(default='Trading in financial markets involves significant risk to your invested capital. Before starting, ensure you fully understand the risks and receive the necessary training. Never invest money you cannot afford to lose. All information provided on "Brokers Times" is for educational and informational purposes only and does not constitute investment advice.')),
                ('footer_risk_warning_ar', models.TextField(default='ينطوي التداول في الأسواق المالية على مخاطر كبرى على رأس المال المستثمر. تأكد قبل البدء من فهمك الكامل للمخاطر وتلقيك التدريب اللازم. لا تستثمر أبداً أموالاً لا يمكنك تحمل خسارتها. جميع المعلومات المقدمة في "بروكرز تايمز" هي لأغراض تعليمية وإعلامية فقط ولا تشكل نصيحة استثمارية.')),
                ('footer_col2_title_en', models.CharField(default='Quick Links', max_length=100)),
                ('footer_col2_title_ar', models.CharField(default='روابط سريعة', max_length=100)),
                ('footer_col3_title_en', models.CharField(default='Legal', max_length=100)),
                ('footer_col3_title_ar', models.CharField(default='قانوني', max_length=100)),
                ('footer_contact_text_en', models.TextField(default='Have a question or inquiry? Our team of experts is available to help you at any time.')),
                ('footer_contact_text_ar', models.TextField(default='هل لديك سؤال أو استفسار؟ فريق الخبراء لدينا متاح لمساعدتك في أي وقت.')),
                ('contact_email', models.EmailField(default='support@brokerstimes.com', max_length=254)),
                ('social_share_url', models.URLField(default='https://twitter.com/brokerstimes', max_length=500)),
                ('copyright_text_en', models.TextField(default='&copy; 2026 Brokers Times. All rights reserved. Risk Warning: Trading forex and CFDs involves a high level of risk and can result in the loss of your invested capital.')),
                ('copyright_text_ar', models.TextField(default='&copy; 2026 بروكرز تايمز. جميع الحقوق محفوظة. تحذير المخاطر: تنطوي تداولات الفوركس وعقود الفروقات على مخاطر عالية وقد تؤدي لخسارة رأس المال.')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
