# Generated by Django 6.0.6 on 2026-06-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('best_brokers', '0008_bestbrokerslist_country_flag'),
        ('pages', '0004_footerlink_footerregulatorybadge_headerlink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='compare_dropdown_lists',
            field=models.ManyToManyField(blank=True, related_name='compare_settings', to='best_brokers.bestbrokerslist', verbose_name='Compare Dropdown Pages'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_logo',
            field=models.ImageField(blank=True, null=True, upload_to='site_settings/', verbose_name='Brand Logo'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='top_10_dropdown_lists',
            field=models.ManyToManyField(blank=True, related_name='top_10_settings', to='best_brokers.bestbrokerslist', verbose_name='Top 10 Brokers Dropdown Pages'),
        ),
    ]
