# Generated by Django 6.0.6 on 2026-06-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0010_alter_broker_id_alter_brokeraccounttype_id_and_more'),
        ('pages', '0005_sitesettings_compare_dropdown_lists_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='top_10_dropdown_brokers',
            field=models.ManyToManyField(blank=True, related_name='top_10_dropdown_settings', to='brokers.broker', verbose_name='Top 10 Brokers Dropdown (Direct)'),
        ),
    ]
