# Generated by Django 6.0.6 on 2026-06-16 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_sitesettings_top_10_dropdown_brokers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='top_10_dropdown_lists',
        ),
    ]
