# Generated by Django 6.0.6 on 2026-06-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_alter_category_id_alter_depositlimit_id_and_more'),
        ('pages', '0007_remove_sitesettings_top_10_dropdown_lists'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footerlink',
            options={'ordering': ['order'], 'verbose_name': '🔻 رابط الفوتر', 'verbose_name_plural': '🔻 روابط الفوتر'},
        ),
        migrations.AlterModelOptions(
            name='footerregulatorybadge',
            options={'ordering': ['order'], 'verbose_name': '🏅 شارة تنظيمية (فوتر)', 'verbose_name_plural': '🏅 الشارات التنظيمية (فوتر)'},
        ),
        migrations.AlterModelOptions(
            name='headerlink',
            options={'ordering': ['order'], 'verbose_name': '🔝 رابط الهيدر', 'verbose_name_plural': '🔝 روابط الهيدر'},
        ),
        migrations.AlterModelOptions(
            name='homepagesettings',
            options={'verbose_name': 'إعدادات الصفحة الرئيسية', 'verbose_name_plural': 'إعدادات الصفحة الرئيسية'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'إعدادات الموقع العامة', 'verbose_name_plural': 'إعدادات الموقع العامة'},
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='homepage_assets',
            field=models.ManyToManyField(blank=True, help_text='اختر الأدوات التي ستظهر في الصفحة الرئيسية. اتركها فارغة لعرض الكل.', related_name='homepage_settings', to='categories.financialasset', verbose_name='📈 الأدوات المالية المعروضة (Financial Instruments)'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='homepage_platforms',
            field=models.ManyToManyField(blank=True, help_text='اختر المنصات التي ستظهر في الصفحة الرئيسية. اتركها فارغة لعرض الكل.', related_name='homepage_settings', to='categories.tradingplatform', verbose_name='🖥️ منصات التداول المعروضة (Trading Platforms)'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='homepage_regulators',
            field=models.ManyToManyField(blank=True, help_text='اختر الهيئات التي ستظهر في الصفحة الرئيسية. اتركها فارغة لعرض الكل.', related_name='homepage_settings', to='categories.regulator', verbose_name='🛡️ هيئات الرقابة المعروضة (Regulations & Licenses)'),
        ),
    ]
