# Generated by Django 6.0.6 on 2026-06-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_footerlink_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='site_icon',
            field=models.ImageField(blank=True, null=True, upload_to='site_settings/', verbose_name='Site Icon / Favicon'),
        ),
    ]
