# Generated by Django 6.0.6 on 2026-06-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_sitesettings_site_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='الاسم / Name')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني / Email')),
                ('subject', models.CharField(max_length=255, verbose_name='الموضوع / Subject')),
                ('message', models.TextField(verbose_name='الرسالة / Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال / Sent At')),
                ('is_read', models.BooleanField(default=False, verbose_name='تم القراءة / Is Read')),
            ],
            options={
                'verbose_name': '📨 رسالة اتصال',
                'verbose_name_plural': '📨 رسائل الاتصال',
                'ordering': ['-created_at'],
            },
        ),
    ]
