# Generated by Django 6.0.6 on 2026-06-13 18:08

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brokers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestBrokersList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_ar', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_title_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_description', models.TextField(blank=True)),
                ('seo_description_ar', models.TextField(blank=True, null=True)),
                ('seo_description_en', models.TextField(blank=True, null=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='best_brokers/')),
                ('content', ckeditor.fields.RichTextField(blank=True)),
                ('content_ar', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('content_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BestBrokersListFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('question_ar', models.CharField(max_length=255, null=True)),
                ('question_en', models.CharField(max_length=255, null=True)),
                ('answer', models.TextField()),
                ('answer_ar', models.TextField(null=True)),
                ('answer_en', models.TextField(null=True)),
                ('order', models.IntegerField(default=0)),
                ('best_brokers_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='best_brokers.bestbrokerslist')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BestBrokersListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('best_brokers_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='best_brokers.bestbrokerslist')),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_broker_items', to='brokers.broker')),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('best_brokers_list', 'broker')},
            },
        ),
    ]
