# Generated by Django 6.0.6 on 2026-06-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('best_brokers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestbrokerslist',
            name='featured_image_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bestbrokerslist',
            name='featured_image_alt_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bestbrokerslist',
            name='featured_image_alt_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
