# Generated by Django 5.2.15 on 2026-06-14 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('best_brokers', '0003_remove_bestbrokerslist_content_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestbrokerslist',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='bestbrokerslist',
            name='featured_image_alt_en',
        ),
        migrations.RemoveField(
            model_name='bestbrokerslist',
            name='seo_description_en',
        ),
        migrations.RemoveField(
            model_name='bestbrokerslist',
            name='seo_title_en',
        ),
        migrations.RemoveField(
            model_name='bestbrokerslist',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='bestbrokerslistfaq',
            name='answer_en',
        ),
        migrations.RemoveField(
            model_name='bestbrokerslistfaq',
            name='question_en',
        ),
        migrations.RemoveField(
            model_name='bestbrokerslistitem',
            name='description_en',
        ),
    ]
