# Generated by Django 6.0.6 on 2026-06-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('best_brokers', '0004_remove_bestbrokerslist_content_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestbrokerslistitem',
            name='custom_deposit',
            field=models.CharField(blank=True, help_text='Custom deposit display text (e.g. $0 (Classic Account))', max_length=100),
        ),
        migrations.AddField(
            model_name='bestbrokerslistitem',
            name='headline',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bestbrokerslistitem',
            name='highlights',
            field=models.TextField(blank=True, help_text='One highlight per line / ميزة واحدة في كل سطر'),
        ),
        migrations.AlterField(
            model_name='bestbrokerslist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bestbrokerslistfaq',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bestbrokerslistitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
