# Generated by Django 6.0.6 on 2026-06-15 14:17

import sortedm2m.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('best_brokers', '0005_bestbrokerslistitem_custom_deposit_and_more'),
        ('brokers', '0010_alter_broker_id_alter_brokeraccounttype_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestbrokerslist',
            name='selected_brokers',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='brokers.broker', verbose_name='قائمة الشركات المحددة لهذه الصفحة'),
        ),
    ]
