# Generated by Django 6.0.6 on 2026-06-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('best_brokers', '0006_bestbrokerslist_selected_brokers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestbrokerslist',
            name='selected_brokers',
        ),
        migrations.AddField(
            model_name='bestbrokerslist',
            name='is_global',
            field=models.BooleanField(default=False, help_text='إذا تم تفعيلها، ستظهر هذه القائمة في شورت كود [brokers_list] في جميع الصفحات', verbose_name='قائمة عالمية (Global List)'),
        ),
    ]
