# Generated by Django 6.0.6 on 2026-06-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('best_brokers', '0007_remove_bestbrokerslist_selected_brokers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestbrokerslist',
            name='country_flag',
            field=models.CharField(blank=True, choices=[('', 'No Flag / بدون علم'), ('ae', 'UAE / الإمارات 🇦🇪'), ('sa', 'Saudi Arabia / السعودية 🇸🇦'), ('gb', 'United Kingdom / بريطانيا 🇬🇧'), ('cy', 'Cyprus / قبرص 🇨🇾'), ('au', 'Australia / أستراليا 🇦🇺'), ('kw', 'Kuwait / الكويت 🇰🇼'), ('bh', 'Bahrain / البحرين 🇧🇭'), ('qa', 'Qatar / قطر 🇶🇦'), ('om', 'Oman / عمان 🇴🇲'), ('jo', 'Jordan / الأردن 🇯🇴'), ('eg', 'Egypt / مصر 🇪🇬'), ('us', 'United States / أمريكا 🇺🇸')], default='', max_length=10, verbose_name='علم الدولة (Country Flag)'),
        ),
    ]
