# Generated by Django 5.2.15 on 2026-06-14 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_remove_category_name_ar_remove_depositlimit_name_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='depositlimit',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='financialasset',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='headquarters',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='islamicaccount',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='regulator',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='tradingplatform',
            name='name_en',
        ),
    ]
