# Generated by Django 5.2.15 on 2026-06-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_remove_category_name_en_remove_depositlimit_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialasset',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='category_icons/'),
        ),
        migrations.AddField(
            model_name='regulator',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='category_icons/'),
        ),
        migrations.AddField(
            model_name='tradingplatform',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='category_icons/'),
        ),
    ]
